title: Yu Zefan's Homepage
page-top-title: Yu Zefan
top-section-bg-text: Be what you wanna be
home-subtitle: Yourname&ensp;|&ensp;yzFFF
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
