title: Yu Zefan's Homepage
page-top-title: yzFFF
top-section-bg-text: Welcome to MyPage!
#home-subtitle: Yourname&ensp;|&ensp;yzFFF&ensp
home-subtitle: Yu Zefan&ensp
copyright-text: '&copy; yzFFF 2023-2025. All Rights Reserved.'
